# Generated by Django 2.2.4 on 2020-10-19 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
            options={
                'verbose_name': ('sap_persona',),
                'verbose_name_plural': ('sap_personas',),
                'db_table': 'sap_personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='modulo_principal.Persona')),
            ],
            options={
                'verbose_name': 'sap_usuario',
                'verbose_name_plural': 'sap_usuarios',
                'db_table': 'sap_usuario',
            },
        ),
    ]
